export const itemdata=[
  {
    id:1,
    name: 'Abhish Mohanty',
    analysisType: 'Premium',
    BTCUSDT: 'Bitcoin/Tether',
    exchange: 'Binance',
    timeFrame: '4H',
    market: 'Futures',
    method: 'Swing Trading',
    position: 'Short',
    leverage: '5X',
    profit: '0.10$',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis dolore dolorum sunt ipsam molestiae quasi volupt',
    view:'1,967,381',
    buy:'471,291',
    date:'12-15-2021',
    time:'23:18:51'
  },
  {
    id:2,
    name: 'Hooman Farzaneh',
    analysisType: 'Premium',
    BTCUSDT: 'Bitcoin/Tether',
    exchange: 'Binance',
    timeFrame: '1H',
    market: 'Futures',
    method: 'Swing Trading',
    position: 'Short',
    leverage: '10X',
    profit: '0.8$',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis dolore dolorum sunt ipsam molestiae quasi volupt',
    view:'2,967,381',
    buy:'471,291',
    date:'01-05-2021',
    time:'02:18:51'
  },
  {
    id:1,
    name: 'Abhish Mohanty',
    analysisType: 'Premium',
    BTCUSDT: 'Bitcoin/Tether',
    exchange: 'Binance',
    timeFrame: '4H',
    market: 'Futures',
    method: 'Swing Trading',
    position: 'Short',
    leverage: '5X',
    profit: '0.10$',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis dolore dolorum sunt ipsam molestiae quasi volupt',
    view:'1,967,381',
    buy:'471,291',
    date:'12-15-2021',
    time:'23:18:51'
  },
  {
    id:1,
    name: 'Abhish Mohanty',
    analysisType: 'Premium',
    BTCUSDT: 'Bitcoin/Tether',
    exchange: 'Binance',
    timeFrame: '4H',
    market: 'Futures',
    method: 'Swing Trading',
    position: 'Short',
    leverage: '5X',
    profit: '0.10$',
    desc: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis dolore dolorum sunt ipsam molestiae quasi volupt',
    view:'1,967,381',
    buy:'471,291',
    date:'12-15-2021',
    time:'23:18:51'
  }
]